# Generated by Django 3.0 on 2021-09-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=150)),
                ('respuesta_1', models.CharField(max_length=150)),
                ('respuesta_2', models.CharField(max_length=150)),
                ('correcta', models.CharField(max_length=150)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.Categoria')),
            ],
        ),
    ]
